### ISSUE TITLE
Fetch API cannot load...

### ISSUE THREAD

**Issue by EstesE** [kellyselden/ember-data-fetch-support#23]
What is the correct way to make changes to the headers?

```
import DS from 'ember-data';
import JSONAPIAdapter from 'ember-data/adapters/json-api';
import FetchSupport from 'ember-data-fetch-support/mixins/fetch-support';

export default DS.JSONAPIAdapter.extend(FetchSupport, {
    host: 'https://xxx.xxx.com',
    headers: {
        'Authorization': 'bearer xxxxxxxxxxxx'
    }
});
```

Error:

> Fetch API cannot load https://xxxxxxx. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by kellyselden** [comment]
I'm not sure off the top of my head what the issue is. I'll try to find some time to dig into this. Thanks for the report.

**Comment by EstesE** [comment]
Could you give an example of how this should work? Something with an adapter & route?
